//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusInfoAssignment.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BusInfo
    {
        public int BusID { get; set; }
        [Required]
        public string BoardingPoint { get; set; }
        [Required]
        [DataType(DataType.Date)]
        public DateTime TravelDate { get; set; }
        [Required]
        public Nullable<decimal> Amount { get; set; }
        [Required]
        [Range(1,5,ErrorMessage ="Please enter value between 1 to 5")]
        public Nullable<int> Rating { get; set; }
    }
}
